import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import Provider from '@/app/_trpc/Provider';
import { CookiesProvider } from 'next-client-cookies/server';
import { cn } from '@/utils/utils';

// ใส่ font ที่เราต้องการใช้งาน
const notoSansThai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  subsets: ["latin","thai"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={cn('min-h-screen bg-background font-noto-sans-thai antialiased', notoSansThai.variable)}>
				<CookiesProvider>
					<Provider>{children}</Provider>
				</CookiesProvider>
			</body>
		</html>
	);
}
